---

- name: Rollback Demo Environment
  hosts: linux
  become: true

  roles:
    - common_cleanup
    - users_cleanup
    # - report_cleanup

- name: Cleanup Windows
  hosts: windows

  roles:
    - windows_cleanup
...

