---
- name: Linux Baseline Configuration
  hosts: linux
  become: true

  roles:
    - role: common_deploy
      tags:
        - common_deploy

    - role: users_deploy
      tags:
        - users_deploy
        
    - role: rhel_baseline
      tags:
        - rhel_baseline

- name: Windows Baseline
  hosts: windows

  roles:
    - role: windows_baseline
      tags: 
        - windows

    # - role: report
    #   tags:
    #     - report    
...
