all:
  children:

    linux:
      hosts:
        localhost:
          ansible_connection: local

        localhost.localdomain:
          ansible_host: 192.168.1.80
    windows:
      hosts:
        windows-pc:
          ansible_host: 192.168.1.182
