---
- name: Install common packages
  ansible.builtin.package:
    name: "{{ common_packages }}"
    state: present

- name: Deploy MOTD
  ansible.builtin.template:
    src: motd.j2
    dest: /etc/motd
